export const TRUSTED_SITES = [
  "k12dive.com",
  "the74million.org",
  "chalkbeat.org",
  "edsurge.com",
  "hechingerreport.org",
  "edutopia.org",
  "kqed.org",
  "edsource.org",
  "ednc.org",
  "eschoolnews.com",
  "edtechmagazine.com",
  "districtadministration.com",
  "edweek.org",
  "educationweek.org",
  "apnews.com",
  "npr.org",
  "pbs.org",
  "reuters.com",
  "nytimes.com",
  "washingtonpost.com",
  "politico.com"
];

export const SOURCE_TIERS = {
  tierA: {
    govPatterns: [
      ".gov",
      "legislature.",
      "legis.",
      "senate.",
      "assembly.",
      "house."
    ],
    localJournalism: [
      "texastribune.org",
      "denverpost.com",
      "startribune.com",
      "seattletimes.com",
      "bostonglobe.com",
      "latimes.com",
      "sfchronicle.com",
      "inquirer.com",
      "chicagotribune.com",
      "miamiherald.com",
      "tampabay.com",
      "ajc.com",
      "dispatch.com",
      "cleveland.com",
      "freep.com",
      "oregonlive.com",
      "baltimoresun.com",
      "virginiamercury.com",
      "coloradosun.com",
      "post-gazette.com"
    ],
    stateEducation: [
      "edsource.org",
      "ednc.org"
    ],
    national: [
      "apnews.com",
      "reuters.com",
      "nytimes.com",
      "washingtonpost.com",
      "politico.com",
      "npr.org",
      "pbs.org"
    ]
  },
  tierB: {
    domains: [
      "chalkbeat.org",
      "the74million.org",
      "k12dive.com",
      "edweek.org",
      "educationweek.org",
      "edsurge.com",
      "hechingerreport.org",
      "edutopia.org",
      "eschoolnews.com",
      "districtadministration.com",
      "brookings.edu",
      "rand.org"
    ],
    localTvPatterns: [
      "khou",
      "kxan",
      "wfaa",
      "wcnc",
      "wpxi",
      "wsoc",
      "wxia",
      "wkyc",
      "kmov",
      "ksdk"
    ]
  },
  tierC: {
    domains: [
      "patch.com",
      "examiner.com",
      "msn.com",
      "yahoo.com",
      "aol.com",
      "newsbreak.com",
      "prweb.com",
      "prnewswire.com",
      "businesswire.com",
      "globenewswire.com"
    ],
    patterns: [
      "press-release",
      "press_release",
      "/sponsored/",
      "/partner-content/"
    ]
  }
} as const;

export const DOMAIN_STATE_MAP: Record<string, string> = {
  "texastribune.org": "Texas",
  "dallasnews.com": "Texas",
  "houstonchronicle.com": "Texas",
  "chron.com": "Texas",
  "statesman.com": "Texas",
  "expressnews.com": "Texas",
  "star-telegram.com": "Texas",
  "latimes.com": "California",
  "sfchronicle.com": "California",
  "sfgate.com": "California",
  "sacbee.com": "California",
  "sandiegouniontribune.com": "California",
  "ocregister.com": "California",
  "mercurynews.com": "California",
  "edsource.org": "California",
  "tampabay.com": "Florida",
  "sun-sentinel.com": "Florida",
  "miamiherald.com": "Florida",
  "orlandosentinel.com": "Florida",
  "jacksonville.com": "Florida",
  "nydailynews.com": "New York",
  "newsday.com": "New York",
  "lohud.com": "New York",
  "democratandchronicle.com": "New York",
  "buffalonews.com": "New York",
  "inquirer.com": "Pennsylvania",
  "post-gazette.com": "Pennsylvania",
  "pennlive.com": "Pennsylvania",
  "chicagotribune.com": "Illinois",
  "suntimes.com": "Illinois",
  "cleveland.com": "Ohio",
  "dispatch.com": "Ohio",
  "cincinnati.com": "Ohio",
  "freep.com": "Michigan",
  "detroitnews.com": "Michigan",
  "mlive.com": "Michigan",
  "ajc.com": "Georgia",
  "charlotteobserver.com": "North Carolina",
  "newsobserver.com": "North Carolina",
  "ednc.org": "North Carolina",
  "azcentral.com": "Arizona",
  "tucson.com": "Arizona",
  "denverpost.com": "Colorado",
  "coloradosun.com": "Colorado",
  "seattletimes.com": "Washington",
  "bostonglobe.com": "Massachusetts",
  "boston.com": "Massachusetts",
  "startribune.com": "Minnesota",
  "jsonline.com": "Wisconsin",
  "indystar.com": "Indiana",
  "stltoday.com": "Missouri",
  "kansascity.com": "Missouri",
  "tennessean.com": "Tennessee",
  "baltimoresun.com": "Maryland",
  "virginiamercury.com": "Virginia",
  "dailypress.com": "Virginia",
  "oregonlive.com": "Oregon",
  "reviewjournal.com": "Nevada",
  "desmoinesregister.com": "Iowa",
  "courier-journal.com": "Kentucky",
  "nola.com": "Louisiana",
  "theadvocate.com": "Louisiana",
  "al.com": "Alabama",
  "oklahoman.com": "Oklahoma",
  "thestate.com": "South Carolina",
  "postandcourier.com": "South Carolina",
  "ctpost.com": "Connecticut",
  "courant.com": "Connecticut",
  "sltrib.com": "Utah",
  "deseret.com": "Utah",
  "arkansasonline.com": "Arkansas",
  "kansas.com": "Kansas",
  "clarionledger.com": "Mississippi",
  "abqjournal.com": "New Mexico",
  "omaha.com": "Nebraska",
  "wvgazettemail.com": "West Virginia",
  "staradvertiser.com": "Hawaii",
  "idahostatesman.com": "Idaho",
  "pressherald.com": "Maine",
  "unionleader.com": "New Hampshire",
  "providencejournal.com": "Rhode Island",
  "billingsgazette.com": "Montana",
  "delawareonline.com": "Delaware",
  "argusleader.com": "South Dakota",
  "inforum.com": "North Dakota",
  "adn.com": "Alaska",
  "burlingtonfreepress.com": "Vermont",
  "trib.com": "Wyoming"
};
